export const UPDATE_TAX_YEAR = 'UPDATE_TAX_YEAR';
export const UPDATE_PAYER = "UPDATE_PAYER";
export const UPDATE_RECIPIENT = "UPDATE_RECIPIENT";
export const UPDATE_INCOME = "UPDATE_INCOME";
export const UPDATE_EMAIL = "UPDATE_EMAIL";

export const VALIDATE_PAYER = "VALIDATE_PAYER";
export const VALIDATE_RECIPIENT = "VALIDATE_RECIPIENT";
export const VALIDATE_INCOME = "VALIDATE_INCOME";
export const VALIDATE_EMAIL = "VALIDATE_EMAIL";